version: 0.2

env:
  variables:
    SRC_DIR: src/github.com/ryno75/gonzo

phases:
  install:
    commands:
      - echo Build started on `date`
      - echo "ENV Vars"
      - echo "========"
      - env
      - echo Installing Go Dep...
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  pre_build:
    commands:
      - echo Resolving Dependencies...
      - dep ensure
  build:
    commands:
      - echo Compiling gonzo...
      - go build main.go
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - gonzo
    - appspec.yml
  discard-paths: yes
