version: 0.2

env:
  variables:
    FOO: src/github.com/ryno75/gonzo
    #SRC_DIR: src/github.com/ryno75/gonzo

phases:
  install:
    commands:
      - echo Build started on `date`
      - echo "ENV Vars"
      - echo "========"
      - env
      #- echo Installing Go Dep...
      #- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  pre_build:
    commands:
      #- echo Resolving Dependencies...
      #- dep ensure
      - echo Debugging...
      - echo GOPATH contents...
      - if $(which tree &> /dev/null); then tree /go/src; fi
      - if [ -e /go/src/github.com/ryno75/gonzo ]; then ls -al /go/src/github.com/ryno75/gonzo; fi
      - ls -al $PWD/../
      - echo PWD contents...
      - ls -al $PWD
  build:
    commands:
      - echo Compiling gonzo binary for amd64 Linux...
      - env GOOS=linux GOARCH=amd64 go build -o gonzo main.go
      - echo Compiling gonzo executable for amd64 Windows...
      - env GOOS=windows GOARCH=amd64 go build -o gonzo.exe main.go
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - gonzo
    - gonzo.exe
    - appspec.yml
  discard-paths: yes
